### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [170]:
import numpy as np

In [171]:
import random
vector_uniform = np.array([random.uniform(0, 1) for _ in range(10)])
# АБО простіше :
# vector_uniform = np.random.uniform(0, 1, size=10)

vector_rand = np.random.rand(10)

print('Вектор методом random.uniform:')
display(vector_uniform)
print('Вектор методом np.random.rand:')
display(vector_rand)

Вектор методом random.uniform:


array([0.06757813, 0.36724081, 0.84731775, 0.1870912 , 0.9958691 ,
       0.10150093, 0.52639885, 0.18525401, 0.84062222, 0.27893607])

Вектор методом np.random.rand:


array([0.71909021, 0.17838499, 0.22070348, 0.36440264, 0.16813269,
       0.29161108, 0.81380624, 0.12849139, 0.50485719, 0.7356357 ])

In [172]:
matrix = np.array([[11, 14, 17],
                   [20, 23, 26],
                   [29, 32, 35]])   
matrix_arange = np.arange(11, 36, 3).reshape(3, 3)

print('Однакові матриці, створені двома різними способами:')
display(matrix, matrix_arange)

Однакові матриці, створені двома різними способами:


array([[11, 14, 17],
       [20, 23, 26],
       [29, 32, 35]])

array([[11, 14, 17],
       [20, 23, 26],
       [29, 32, 35]])

In [173]:
print('Розміри вектору та матриці:')
display(vector_rand.shape, matrix.shape)

Розміри вектору та матриці:


(10,)

(3, 3)


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [174]:
# Далі вектор vector_rand це і є vector
print('Початковий вектор:')
display(vector_rand)
print('Початкова матриця:')
display(matrix)

Початковий вектор:


array([0.71909021, 0.17838499, 0.22070348, 0.36440264, 0.16813269,
       0.29161108, 0.81380624, 0.12849139, 0.50485719, 0.7356357 ])

Початкова матриця:


array([[11, 14, 17],
       [20, 23, 26],
       [29, 32, 35]])

In [175]:
vector_plus = np.round(vector_rand + 10, 2)
# АБО:
# vector_plus = np.round(np.add(vector_rand, 10), 2)

print('Початковий вектор + 10 до значень і їх округлення:')
display(vector_plus)

Початковий вектор + 10 до значень і їх округлення:


array([10.72, 10.18, 10.22, 10.36, 10.17, 10.29, 10.81, 10.13, 10.5 ,
       10.74])

In [176]:
matrix_mult = matrix * 2
# АБО:
# matrix_mult = np.multiply(matrix, 2)

print('Початкова матриця * 2 кожного елементу:')
display(matrix_mult)

Початкова матриця * 2 кожного елементу:


array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [177]:
vector_sqr = vector_rand**2
# АБО:
# vector_sqr = np.square(vector_rand)

print('Піднесення до квадрату кожного елементу початкового вектору:')
display(vector_sqr)

Піднесення до квадрату кожного елементу початкового вектору:


array([0.51709073, 0.0318212 , 0.04871002, 0.13278928, 0.0282686 ,
       0.08503702, 0.6622806 , 0.01651004, 0.25488078, 0.54115989])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [178]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [179]:
# Щоб результуюча матриця була розміром 2x2 потрібно B помножити на A
result_matrix = np.dot(B, A)
print('Множення матриць BA:')
display(result_matrix, result_matrix.shape)

Множення матриць BA:


array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

(2, 2)

In [180]:
# В даному випадку можемо помножити result_matrix з розмірністю 2х2 на матрицю C розмірністю 2x1 (навпаки не вийде)
# Розмірність результуючої матриці буде 2x1
result_matrix_C = np.dot(result_matrix, C)
print('Множення result_matrix на C:')
display(result_matrix_C, result_matrix_C.shape)

Множення result_matrix на C:


array([[0.5202],
       [0.2846]])

(2, 1)

In [181]:
# В даному випадку можемо помножити result_matrix з розмірністю 2х2 на матрицю D розмірністю 2x2 (можна і навпаки, але результат буде інший)
# Розмірність результуючої матриці буде 2x2
result_matrix_D = np.dot(result_matrix, D)
print('Множення result_matrix на D:')
display(result_matrix_D, result_matrix_D.shape)

Множення result_matrix на D:


array([[0.5202, 0.7281],
       [0.2846, 0.2034]])

(2, 2)


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [182]:
print('Матриця result_matrix:')
display(result_matrix)

Матриця result_matrix:


array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [183]:
result_matrix_T = result_matrix.T
print('Транспонована матриця до result_matrix:')
display(result_matrix_T)

Транспонована матриця до result_matrix:


array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [184]:
vector_rand_T = vector_rand.T
print('Початковий вектор:')
display(vector_rand, vector_rand.shape)
print('Транспонований вектор:')
display(vector_rand_T, vector_rand_T.shape)
# Бачимо, що змін не відбулося, адже для NumPy цей вектор - це 1-вимірний масив, а не стовпчик або рядок

Початковий вектор:


array([0.71909021, 0.17838499, 0.22070348, 0.36440264, 0.16813269,
       0.29161108, 0.81380624, 0.12849139, 0.50485719, 0.7356357 ])

(10,)

Транспонований вектор:


array([0.71909021, 0.17838499, 0.22070348, 0.36440264, 0.16813269,
       0.29161108, 0.81380624, 0.12849139, 0.50485719, 0.7356357 ])

(10,)

In [185]:
column_vector = np.expand_dims(vector_rand, axis=1)
print('Використання expand_dims:')
display(column_vector)
display(vector_rand.shape, column_vector.shape)
# Бачимо, що відбулося перетворення одновимірного вектора у стовпчиковий вектор з розміром (10, 1)

Використання expand_dims:


array([[0.71909021],
       [0.17838499],
       [0.22070348],
       [0.36440264],
       [0.16813269],
       [0.29161108],
       [0.81380624],
       [0.12849139],
       [0.50485719],
       [0.7356357 ]])

(10,)

(10, 1)

In [186]:
column_vector_T = column_vector.T
print('Транспонований вектор column_vector:')
display(column_vector_T,column_vector_T.shape)
# Отже, транспонування працює коректно для двох і вище вимірних масивів

Транспонований вектор column_vector:


array([[0.71909021, 0.17838499, 0.22070348, 0.36440264, 0.16813269,
        0.29161108, 0.81380624, 0.12849139, 0.50485719, 0.7356357 ]])

(1, 10)